### ISSUE TITLE
Service Integration Tracking

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#536]
This issue is used to track all services integration. We will record the status of services, including:

- [stable](#stable): implemented required features and have passed all integration tests.
- [beta](#beta): implemented required features but didn't pass the integration tests.
- [alpha](#alpha): implementing features, under development.
- [planned](#planned): not implement anything.
- [canceled](#canceled): services can't be implemented for now.

## Stable

| name | build | description |
| - | - | - |
| azblob | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-azblob.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-azblob.yml) | - |
| azfile | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-azfile.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-azfile.yml) | - |
| bos |  [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-bos.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-bos.yml)| Baidu Cloud Object Storage |
| cos |  [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-cos.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-cos.yml)|  Tencent Cloud Storage |
| dropbox | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-dropbox.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-dropbox.yml) | - |
| fs |  [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-fs.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-fs.yml) | POSIX file system |
| ftp | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-ftp.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-ftp.yml) | - |
| gcs | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-gcs.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-gcs.yml) | - |
| gdrive | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-gdrive.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-gdrive.yml)| Google Drive |
| hdfs | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-hdfs.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-hdfs.yml) | - |
| ipfs | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-ipfs.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-ipfs.yml) | - |
| kodo |  [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-kodo.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-kodo.yml) | Qiniu |
| memory |  [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-memory.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-memory.yml) | Memory file system |
| minio | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-minio.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-minio.yml) | - |
| obs | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-obs.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-obs.yml)  | SDK doesn't [support read with offset](https://github.com/beyondstorage/go-storage/issues/959) |
| oss |  [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-oss.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-oss.yml) | Aliyun OSS |
| qingstor | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-qingstor.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-qingstor.yml) |  QingCloud Object Storage |
| s3 | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-s3.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-s3.yml) | [Failed test on minio](https://github.com/beyondstorage/go-storage/issues/860) |
| storj | [![](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-storj.yml/badge.svg)](https://github.com/beyondstorage/go-storage/actions/workflows/services-test-storj.yml) | - |

## Beta

- [ ] onedrive: https://github.com/beyondstorage/go-storage/issues/923
- [ ] uss: Upyun

## Alpha

- [ ] webdav
- [ ] tar file format
- [ ] zip file format
- [ ] us3: UCloud Object Storage
- [ ] ocios: OCI Object Storage
- [ ] cephfs

## Planned

> Please leave comments for us if you want to implement one of those services.

---

### Standard Protocol

- [ ] iso file format

### File Storage Services

- [ ] glusterfs (https://github.com/gluster/gogfapi)
- [ ] ufile (UCloud file)
- [ ] LeanFile https://github.com/leancloud/go-sdk/tree/master/leancloud
- [ ] put.io https://github.com/putdotio/go-putio

### Object Storage Services

- [ ] rados
- [ ] Backblaze B2 (No official SDK, https://github.com/kothar/go-backblaze)
- [ ] Huawei Object Storage Service (https://github.com/huaweicloud/huaweicloud-sdk-go-obs)
- [ ] Sina Cloud Storage (https://github.com/SinaCloudStorage/SinaCloudStorage-SDK-Go)
- [ ] NetEase Object Storage (https://github.com/NetEase-Object-Storage/nos-golang-sdk)
- [ ] LeanObject (https://github.com/leancloud/go-sdk/)
- [ ] Swift https://github.com/ncw/swift

### Key-Value Storage Services

- [ ] TiKV
- [ ] Redis
- [ ] KVSSD (maybe?)

### Distributed Storage Services

- [ ] filecoin

### Cloud Drive Services

- [ ] iCloud (No stable SDK)
  - Take https://github.com/MauriceConrad/iCloud-API for reference
- [ ] [Baidu Netdisk](https://yun.baidu.com/) https://github.com/jsyzchen/pan
- [ ] [Aliyun Drive](https://www.aliyundrive.com/) (No stable SDK)
- [ ] NextCloud/ownCloud: https://github.com/partitio/gonextcloud , https://github.com/remogatto/cloud
- [ ] Seafile https://github.com/go-http/seafile
- [ ] Telegram (like https://github.com/xelaj/mtproto )
- [ ] Yandex Disk https://github.com/chibisov/go-yadisk

### Others

- [ ] Synology File Station https://github.com/macpoint/synogo
- [ ] Github / Gitlab (maybe ?)

## Canceled

- [ ] Azure Data Lake Gen1 / Azure Data Lake Gen2 (No golang SDK)
- [x] [ksyun Object Storage (KS3)](https://github.com/ks3sdklib/aws-sdk-go): Fully S3 Compatible, no native SDK
- [x] IBM Cloud Storage Service: Fully S3 Compatible, no native SDK (https://github.com/IBM/ibm-cos-sdk-go is a fork)
- [x] DigitalOcean Space: Fully S3 Compatible, no native SDK
- [x] JCloud Object Storage: Fully S3 Compatible, native SDK is discontinued.
- [ ] CTYun OOS (No golang SDK provided)
- [x] Scaleway Object Storage: Fully S3 Compatible, no native SDK
- [x] ECloud (China Mobile Cloud) Object Storage: Fully S3 Compatible, no native SDK
- [ ] Box (No golang SDK)
