### ISSUE TITLE
Implement GSP-49 Add CreateDir Operation

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#560]
RFC: https://github.com/aos-dev/specs/blob/master/rfcs/49-add-create-dir-operation.md

Please leave a comment telling us what part you would like to do.

## Roadmap

- [x] Add `CreateDir` operation in [specs](https://github.com/aos-dev/specs)
- [x] Update go-storage https://github.com/aos-dev/go-storage/pull/561
- [x] Add integration tests for `CreateDir` https://github.com/beyondstorage/go-integration-test/pull/20
- [x] Implement `CreateDir` in services
  - [x] azblob https://github.com/beyondstorage/go-service-azblob/pull/26 https://github.com/beyondstorage/go-service-azblob/pull/27
  - [x] cos https://github.com/beyondstorage/go-service-cos/pull/28 https://github.com/beyondstorage/go-service-cos/pull/32
  - [x] dropbox https://github.com/beyondstorage/go-service-dropbox/pull/20 https://github.com/beyondstorage/go-service-dropbox/pull/22
  - [x] fs beyondstorage/go-service-fs#45
  - [x] gcs https://github.com/beyondstorage/go-service-gcs/pull/35
  - [x] kodo https://github.com/beyondstorage/go-service-kodo/pull/29
  - [x] oss https://github.com/beyondstorage/go-service-oss/pull/31
  - [x] qingstor https://github.com/beyondstorage/go-service-qingstor/pull/58
  - [x] s3 https://github.com/beyondstorage/go-service-s3/pull/114 https://github.com/beyondstorage/go-service-s3/pull/126
  - [x] uss https://github.com/beyondstorage/go-service-uss/pull/12

**Comment by JinnyYi** [comment]
I have some questions:
- Is it necessary to check the `path` parameter?
  For object storage, may be we need to add `/` at the end of `path`. But  paths may not end with a slash or whitespace in `dropbox`.
- Is it allowed to create root directory?
- How to deal with file and directory with the same name?
  - For file system, a file and a  subdirectory in the same directory with the same name are not allowed.
  - For object storage, `test` and `test/` exist simultaneously is allowed. Should we check whether the file or directory exist if  we implement `CreateDir` through `store.Write("abc/", nil, 0, ps.WithContentType("application/x-directory"))` in object storage?
 - How to deal with creating an existing dir?
   - For file system, create an existing dir will get `File exists` error.
   - For `dropbox`, calling `CreateFolderV2` to create an existing dir will get `path/conflict/folder/.` error.
   - For object storage, calling `PutObject` to create an existing object will overwrite it.
- Impact on other interfaces:
  - `CreateAppend/Create(with MultipartId)/write`: the `path` parameter shoud not be `abc/` liked (`abc/xxx` allowed).
  - `Delete`: Only allowed to delete a file or an empty directory (If allowed to delete recursively, `os.RemoveAll()` should be called in `fs`, `List` need to call first for object storage, `config.Folder` should be set `true` for `uss`)?
  - ...
- How to implement `CreateDir` in `kodo`?
  An alternative way is to `Put` an empty file first, then modify the mimetype to `application/x-directory` through `ChangeMime`. But we will get the `MD5` of the simulated folder from `ListFiles` which is puzzling.

**Comment by Xuanwo** [comment]
Nice question list, I think we should add them in both GSP and CreateDir comments.

---

> Is it necessary to check the `path` parameter?

We can add a limit for `CreateDir`: `path` should not be ended with `/`.

Object storage should add `/` at the end of `path` to simulate a directory.

> Is it allowed to create root directory?

No, and it's not needed: `WorkDir` should be created by services while init.

> How to deal with file and directory with the same name?

It's storage service behavior, let's just follow them. I think it's OK. Just make it clear in `CreateDir`'s comment.

- For fs, we return an error.
- For object storage, we allow `test` and `test/` to exist at the same time.

> How to deal with creating an existing dir?

It's storage service behavior, let's just follow them. I think it's OK. Just make it clear in `CreateDir`'s comment.

- For fs, we return an error.
- For object storage, just overwrite them.

> **Notice**: `CreateDir` for object storage service should be a virtual function, users should enable them and we should add comments for all these limitations.

> CreateAppend/Create(with MultipartId)/write

For all API, we don't allow user input path ends with `/`.

In `Create`, we create a dir object like: `Create("test", ps.WithObjectMode(ObjectModeDir))`

> `Delete`

We only support deleting a single object which means a normal object or an empty dir object.

And we should never call API like `os.RemoveAll()` in our services.

> How to implement CreateDir in `kodo`?

Let's discuss this in kodo's PR.

**Comment by Xuanwo** [comment]
Now we have [GSP-93](https://github.com/beyondstorage/specs/pull/93), the behavior should be changed.

**Comment by JinnyYi** [comment]
Pause for https://github.com/beyondstorage/specs/issues/107.
