### ISSUE TITLE
Add gofmt check in workflows

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#563]
We need to add `gofmt` check to make sure every PR has been formatted.

Like https://github.com/digitalocean/godo/pull/396/files

We should add  the following action `.github/workflows/gofmt.yml` in every golang related repos:

```yaml
name: "gofmt"

on: [ push,pull_request ]

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Format
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi
```

Tips:
- Should be `make build`, as `make build` will format all code.

## Todo Lists

- [x] https://github.com/beyondstorage/go-storage/pull/660
- [x] https://github.com/beyondstorage/go-service-ipfs/pull/8
- [x] https://github.com/beyondstorage/go-coreutils/pull/9
- [x] https://github.com/beyondstorage/go-service-azblob/pull/33
- [x] https://github.com/beyondstorage/go-service-cos/pull/37
- [x] https://github.com/beyondstorage/go-service-dropbox/pull/26
- [x] https://github.com/beyondstorage/go-service-fs/pull/50
- [x] https://github.com/beyondstorage/go-service-gcs/pull/41
- [x] https://github.com/beyondstorage/go-service-kodo/pull/34
- [x] https://github.com/beyondstorage/go-service-oss/pull/35
- [x] https://github.com/beyondstorage/go-service-qingstor/pull/62
- [x] https://github.com/beyondstorage/go-service-s3/pull/140
- [x] https://github.com/beyondstorage/go-service-uss/pull/14
- [x] https://github.com/beyondstorage/go-service-example/pull/8

**Comment by burntcarrot** [comment]
@Xuanwo I have created a PR. Requesting review.

**Comment by Xuanwo** [comment]
@burntcarrot Bravo Work!

**Comment by burntcarrot** [comment]
Phew! That was exhausting, but I guess now we have a good workflow. 😀

Looking forward to contribute more! 🥳
