### ISSUE TITLE
Implement  GSP-87 Feature Gates 

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#587]
## Roadmap

- [x] Update specs https://github.com/beyondstorage/specs/pull/89
- [x] Update go-storage https://github.com/beyondstorage/go-storage/pull/586
- [x] Implement in services
  - [x] azblob
  - [x] cos
  - [x] dropbox
  - [x] fs
  - [x] gcs
  - [x] kodo
  - [x] oss
  - [x] qingstor
  - [x] s3
  - [x] uss
- [x] Implement for services in alpha state
  - [x] go-service-onedrive
  - [x] go-service-gdrive
  - [x] go-service-hdfs
  - [x] go-service-ipfs
  - [x] go-service-minio
  - [x] go-service-ftp
  - [x] go-service-storj
  - [x] go-service-webdav

**Comment by Xuanwo** [comment]
Please also update the service in alpha state, like https://github.com/beyondstorage/go-service-gdrive

**Comment by Prnyself** [comment]
Nicely done!
