### ISSUE TITLE
Implement GSP-93: Add ObjectMode Pair

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#591]
## Roadmap

- [x] Add ObjectMode type https://github.com/beyondstorage/specs/pull/94
- [x] Add type into operations https://github.com/beyondstorage/specs/pull/94
- [ ] Implement all services
