### ISSUE TITLE
Tracking issue for GSP-90: Re-support Initialization Via Connection String

### ISSUE THREAD

**Issue by xxchan** [beyondstorage/go-storage#600]
RFC: https://github.com/beyondstorage/specs/pull/90
- [x] Already implemented in go-storage https://github.com/beyondstorage/go-storage/pull/589
- [x] `go-service-*` only need to update `go-storage` version to master or next release
- [x] add docs and examples for users, and maybe an internal blog for developers
	- [x] site https://github.com/beyondstorage/site/pull/125
	- [x] go-storage README quickstart (& function docstring?) https://github.com/beyondstorage/go-storage/pull/610
	- [x] go-storage-example

**Comment by Xuanwo** [comment]
We need to add docs and examples for users, and maybe an internal blog for developers?
