### ISSUE TITLE
Tracking issue for GSP-86: Add CreateLink Operation

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#611]
- [Rendered GSP](https://github.com/beyondstorage/specs/blob/master/rfcs/86-add-create-link-operation.md)

## Steps

- [x] Add `CreateLink` in definitions (`definitions/operations.toml`) https://github.com/beyondstorage/go-storage/pull/674
- [x] Add linker integration tests (in https://github.com/beyondstorage/go-integration-test)
- [x] Add `virtual_link` features (`definitions/features.toml`)
