### ISSUE TITLE
Tracking issue for GSP-139: Split Specs

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#627]
- [Rendered Proposal](https://github.com/beyondstorage/specs/blob/master/rfcs/139-split-specs.md)

## Steps

- [x] https://github.com/beyondstorage/go-storage/pull/628
- [x] Migrate existing PRs to go-storage (after this change, specs will not accept new proposals anymore)
- [x] Move all issues into go-storage
  - They will be assigned a new number just like we create new issues in go-storage
- [x] https://github.com/beyondstorage/go-storage/pull/652
- [x] Convert specs into archived (read-only)
- [x] Remove `specs` teams in `community` (we don't need this team anymore)
- [ ] Update links to definitions in site and docs (GSP will not changed, so we don't need to update links to GSP)
- [ ] Update all services to reflect codegen changes

**Comment by xxchan** [comment]
types in `service.toml` should be changed to golang types directly?

**Comment by Xuanwo** [comment]
Ooops, yes, we need to update all services.
