### ISSUE TITLE
Tracking issue of GSP-41: Turn Pair Expire into Duration

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#676]
- [Rendered RFC](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/41-turn-pair-expire-into-duration.md)

This is a special case: we will change the type of our global pairs.

At the time we proposal the GSP-41, only one service(qingstor) implement `Reach` and depends on `expire`.

## Affected Services

- [x] qingstor

## Steps

- [x] Add support for `time.Duration` (Update `cmd/definitions/tmpl/service.tmpl` to import `time` package)
- [x] Change pair type from `int` to `time.Duration` (Update `definitions/pairs.toml` pair's type)
- [x] All services that refer to `expire` change to `expire` instead (Rebuild with new `go-storage`)

**Comment by Prnyself** [comment]
@aeinrw Since #681 is merged, could you please implement this change into go-service-qingstor? The related steps are list here.

**Comment by Prnyself** [comment]
Good job! @aeinrw
