### ISSUE TITLE
Tracking issues of go-storage 2021Q3 Roadmap

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#703]
This issue will track tasks that split from [BeyondStorage 2021Q3 Roadmap](https://beyondstorage.io/blog/2021/08/06/2021q3-roadmap)

### Steps

- Implement features required by `Storager`
- Passed integration tests.
- Add docs and examples.
- Update docs in go-storage and site.

### Services

- [x] ftp: FTP
- [x] gdrive: Google Drive
- [x] hdfs: Hadoop Distributed File System
- [x] ipfs: InterPlanetary File System
- [x] memory: data that only in memory
- [x] minio: MinIO
- [ ] onedrive: Microsoft OneDrive
- [ ] storj: StorJ
- [ ] webdav: WebDAV

## Implement more services

We expect to implement 9 of them in 2021Q3.

- [ ] ocios: https://github.com/beyondstorage/go-storage/issues/692
- [ ] glusterfs
- [x] cephfs: https://github.com/beyondstorage/go-service-cephfs
- [x] azfile: https://github.com/beyondstorage/go-service-azfile
- [ ] LeanFile
- [ ] rados
- [x] us3: https://github.com/beyondstorage/go-service-us3
- [x] bos: https://github.com/beyondstorage/go-service-bos
- [x] Huawei Object Storage Service: https://github.com/beyondstorage/go-service-obs
- [ ] LeanObject
- [ ] Swift

## Usability and stability improve

- [x] https://github.com/beyondstorage/go-storage/issues/680
- [x] https://github.com/beyondstorage/go-storage/issues/646
- [ ] New connection string layout
- [ ] go-endpoint support default protocol?

## Related Sprints

- https://github.com/beyondstorage/community/issues/48

**Comment by Xuanwo** [comment]
@abyss-w Would you like to lead “Implement more services” related projects?

**Comment by Xuanwo** [comment]
@JinnyYi Would you like to lead “Usability and stability improve” related projects?

**Comment by JinnyYi** [comment]
> @JinnyYi Would you like to lead “Usability and stability improve” related projects?

Yes. I'll give a rough schedule later if needed.

**Comment by abyss-w** [comment]
> @abyss-w Would you like to lead “Implement more services” related projects?

Can I really do it? I'm worried that I won't be up to the task.

**Comment by Xuanwo** [comment]
@JinnyYi 

> Yes. I'll give a rough schedule later if needed.

Great, how about opening a new issue in go-storage to track it?

@abyss-w 

> Can I really do it? I'm worried that I won't be up to the task.

I think you are perfectly capable of doing it, you just lack some practice. 

How about starting from bos: https://github.com/baidubce/bce-sdk-go? Its API looks much like s3, and we can take go-service-s3 as a reference. And our community is always there for help!

**Comment by abyss-w** [comment]
> I think you are perfectly capable of doing it, you just lack some practice.
> 
> How about starting from bos: https://github.com/baidubce/bce-sdk-go? Its API looks much like s3, and we can take go-service-s3 as a reference. And our community is always there for help!

OK, I can try it!

**Comment by Xuanwo** [comment]
@abyss-w I created repo https://github.com/beyondstorage/go-service-bos

**Comment by Xuanwo** [comment]
2021Q3 is almost over, let's summarize what tasks remain to be completed.

ping @JinnyYi and @abyss-w for comments.

**Comment by JinnyYi** [comment]
`New connection string layout` could be started from the next working week. In achieving `new connection string layout`, it may be necessary to complete `go-endpoint support default protocol`.

**Comment by abyss-w** [comment]
Five services (`glusterfs`, `LeanFile`, `rados`, `Swift`, `LeanObject`) are not yet supported, and `cephfs` is still being implemented.
Are `LeanFile` and `LeanObject` the same project? Their SDKs are the same.
