### ISSUE TITLE
Tracking issues of GSP-700: Config Features and DefaultPairs via Connetion String

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#704]
- RFC PR: https://github.com/beyondstorage/go-storage/pull/700

## Steps

- [x] Generate feature pairs (Allow using `EnableVirtualDir()`)
- [x] Generate default pairs (Allow using `DefaultStorageClass`, as described in GSP)
- [x] Add support in connection string (All using `s3://xxxx?default_storage_class=xxxx`)
- [x] Auto set `StorageFeatures` with input like `EnableVirtualDir` 
- [x] Auto set `DefaultStoragePairs` with input like `DefaultStorageClass`
- [ ] Add docs in site
- [ ] Add examples

**Comment by Xuanwo** [comment]
Great, all code-related work has been done!

**Comment by Xuanwo** [comment]
This issue will be extended by https://github.com/beyondstorage/go-storage/issues/727
