### ISSUE TITLE
Tracking issue for GSP-706: Support HTTP Signer

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#707]
- [RFC PR](https://github.com/beyondstorage/go-storage/pull/706)

## Steps

- [x] Add new interface and operations in definitions.
- [ ] Update docs in site (Add descriptions for the operaiton and a doc for migration from `Reacher` to `HttpSigner`).
- [ ] Implement integration test.

**Comment by Xuanwo** [comment]
ping @JinnyYi , we are woring on https://github.com/beyondstorage/go-storage/pull/729,  maybe we need to update the progress here, and close this issue if we will give up GSP-706?

**Comment by JinnyYi** [comment]
We encountered some problems in the implementation for services. Discussions:

- [How to pass `partIndex` into `QuerySignHTTP` for `WriteMultipart`?](https://forum.beyondstorage.io/t/how-to-pass-partindex-into-querysignhttp-for-writemultipart/192)
- [#beyondstorage@gsp-706:matrix.org](https://matrix.to/#/#beyondstorage@gsp-706:matrix.org)

We plan to split `HTTPSigner` into multiple interfaces and `HTTPSigner` will be deprecated. Here is the ongoing GSP (go-storage proposal) for tracking:

- [GSP-729: Redesign HTTP Signer](https://github.com/beyondstorage/go-storage/pull/729)
