### ISSUE TITLE
Tracking issue of GSP-725: Add Defaultable Property for Pair

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#727]
- [Rendered RFC](https://github.com/beyondstorage/go-storage/pull/725)

## Steps

- [x] Add `defaultable` field in pair (definitions, cmd/specs)
- [x] Remove `defaultable` field in namespace (cmd/specs)
- [x] Generate default pairs for defaultable global pairs and defaultable system pairs (cmd/definitions/type.go)
