### ISSUE TITLE
1st Cleanup Week Roadmap

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#744]
As announced at https://forum.beyondstorage.io/t/1st-cleanup-week-for-go-storage/213, this week (09/06-09/10) is the first cleanup week for go-storage.

We expect to stop any new feature development of go-storage and focus on bugfix, docs like:

- every project's `README.md` update (update links of matrix room, integration tests, and so on)
- go-storage-example enhancement.
- go-storage user guide and developer guide.
- Clean up issues we are working on and plan to do.
- File new issues about any problems that meet (could be solved later)
- ...

**Please feel free to open a new request in this issue!**

## Docs

- [x] https://github.com/beyondstorage/go-storage/issues/743

## Tests

- [x] #745

## Infra

- [x] Auto merge upgrade of go-storage @Xuanwo 

## Behavior

- [ ] https://forum.beyondstorage.io/t/specify-the-behavior-for-writing-empty-file/204/2
- [ ] https://forum.beyondstorage.io/t/specify-the-behavior-of-path/195/2
- [ ] https://forum.beyondstorage.io/t/proposal-adopt-commitizen-conventional-commit-types/193/2

**Comment by JinnyYi** [comment]
I'll clean up issues related with HTTP Signer, including docs and example. In addition, I'd like to take over `Bebavior`,  go-storage-example enhancement.

**Comment by abyss-w** [comment]
I can take over the `Tests` part first. I can also take over the `Behavior` part(the path or write empty file).

**Comment by Xuanwo** [comment]
Hi, it looks like we are working on the `Behavior` part now. Maybe we need to leave them as the last part? 

Here is some projects reply to the new releases of various services. How about finishing #743 and #745 first, and release new versions for all our services first?

**Comment by JinnyYi** [comment]
> How about finishing #743 and #745 first, and release new versions for all our services first?

I can embark on  https://github.com/beyondstorage/go-storage/issues/743 refer to https://github.com/beyondstorage/go-service-s3/pull/208.

**Comment by Xuanwo** [comment]
Nice work!
