### ISSUE TITLE
Tracking issue of GSP-751: Write Empty File Behavior

### ISSUE THREAD

**Issue by abyss-w** [beyondstorage/go-storage#756]
- [Rendered RFC](https://github.com/beyondstorage/go-storage/pull/751)

### steps

- [x] Update the description of `Write` in `go-storage` to include this behavior (definitions)
- [x] https://github.com/beyondstorage/go-integration-test/pull/56
- [x] All services implement this behavior

**Comment by zu1k** [comment]
Some services such as IPFS do not support writing empty files.

**Comment by Xuanwo** [comment]
Yes, it's indeed a question.

See discussion at:

- https://forum.beyondstorage.io/t/topic/204/5
- https://github.com/beyondstorage/go-service-onedrive/pull/17#issuecomment-928711846

We will add feature flags that allow services to declare which feature they have to avoid this problem.
