### ISSUE TITLE
Tracking issue for GSP-749: Unify Path Behavior

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#758]
- [Rendered GSP](https://github.com/beyondstorage/go-storage/pull/749)

## Steps

- [x] Update go-storage
  - Update descriptions for `work_dir` and `ID`, `Path` of `Object`
- [x] Generate code for services that replaces separator with `/`
- [x] Add test cases in go-integration test
  - Basic operation with absolute path
  - Basic operation with path using different separator
  - Add `Object.ID` check for the current tests (Not added as in some services `ID` may be path independent)

## Related issues

This issue will solve following discussions.

- [Specify the behavior of Path](https://forum.beyondstorage.io/t/topic/195)
- [OS-specific path separator problem](https://github.com/beyondstorage/go-service-ftp/issues/22)
