### ISSUE TITLE
Migrate to go-storage v3.4.2 [GS-101]

### ISSUE THREAD

**Issue by BeyondRobot** [beyondstorage/go-storage#805]
## Workflow

- Create the related issue which titled like `Migrate to go-storage v3.4.2` and update links below.
- Finish the migrations.
- Check the todo to mark as finished.

Take https://github.com/aos-dev/go-service-s3/pull/56 as example.

## Todo List

- [x] https://github.com/aos-dev/go-service-s3
- [x] https://github.com/aos-dev/go-service-gcs
- [x] https://github.com/aos-dev/go-service-cos
- [x] https://github.com/aos-dev/go-service-oss
- [x] https://github.com/aos-dev/go-service-dropbox
- [x] https://github.com/aos-dev/go-service-azblob
- [x] https://github.com/aos-dev/go-service-kodo
- [x] https://github.com/aos-dev/go-service-uss

___

Automatically created from [Linear (#101)](https://linear.app/beyondstorage/issue/GS-101/migrate-to-go-storage-v342)

*via LinearSync*
