### ISSUE TITLE
Tracking issue for GSP-86: Add CreateLink Operation [GS-140]

### ISSUE THREAD

**Issue by BeyondRobot** [beyondstorage/go-storage#808]
- [Rendered GSP](https://github.com/beyondstorage/specs/blob/master/rfcs/86-add-create-link-operation.md)

## Steps

- [x] Add `CreateLink` in definitions (`definitions/operations.toml`) https://github.com/beyondstorage/go-storage/pull/674
- [x] Add linker integration tests (in https://github.com/beyondstorage/go-integration-test)
- [x] Add `virtual_link` features (`definitions/features.toml`)

___

Automatically created from [Linear (#140)](https://linear.app/beyondstorage/issue/GS-140/tracking-issue-for-gsp-86-add-createlink-operation)

*via LinearSync*
