### ISSUE TITLE
Roadmap for moving to github.com/aos-dev [GS-85]

### ISSUE THREAD

**Issue by BeyondRobot** [beyondstorage/go-storage#815]
This project will be moved to organation https://github.com/aos-dev for better maintenance and project layout.

Readmap:

- [x] Move this repo to https://github.com/aos-dev/go-storage
- [x] Change import path and upgrade to v2
- [x] Split all service into separate repos during v2 upgrade
- [x] #363 shoule also be implemented during v2 upgrade
- [x] Update docs

___

Automatically created from [Linear (#85)](https://linear.app/beyondstorage/issue/GS-85/roadmap-for-moving-to-githubcomaos-dev)

*via LinearSync*
