### ISSUE TITLE
Tracking issue for GSP-90: Re-support Initialization Via Connection String [GS-135]

### ISSUE THREAD

**Issue by BeyondRobot** [beyondstorage/go-storage#818]
RFC: https://github.com/beyondstorage/specs/pull/90
- [x] Already implemented in go-storage https://github.com/beyondstorage/go-storage/pull/589
- [x] `go-service-*` only need to update `go-storage` version to master or next release
- [x] add docs and examples for users, and maybe an internal blog for developers
	- [x] site https://github.com/beyondstorage/site/pull/125
	- [x] go-storage README quickstart (& function docstring?) https://github.com/beyondstorage/go-storage/pull/610
	- [x] go-storage-example

___

Automatically created from [Linear (#135)](https://linear.app/beyondstorage/issue/GS-135/tracking-issue-for-gsp-90-re-support-initialization-via-connection)

*via LinearSync*
