### ISSUE TITLE
Tracking issue for GSP-826: Add Multipart HTTP Signer Support

### ISSUE THREAD

**Issue by abyss-w** [beyondstorage/go-storage#828]
- [Rendered RFC](https://github.com/beyondstorage/go-storage/pull/826)

## steps
- [ ] Add new interface and operations in `go-storage`(definitions).
- [ ] Add integration tests for `MultipartHTTPSigner` and `QuerySignHTTPDelete` in `go-integration-test`.
- [ ] Update all services that support HTTP signer.

**Comment by Xuanwo** [comment]
Duplicated with https://github.com/beyondstorage/go-storage/issues/827, closed.
