### ISSUE TITLE
Tracking issue of GSP-840: Convert to monorepo

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#841]
- GSP: https://github.com/beyondstorage/go-storage/pull/840

## Roadmap

- [x] Update mod files to v5
- [x] Update mod name to `go.beyondstorage.io`
- [x] Convert `pkg/*` as separate modules (Only credential and endpoint need to be spilt)
  - https://github.com/beyondstorage/go-storage/pull/843
  - https://github.com/beyondstorage/go-storage/pull/845
  - https://github.com/beyondstorage/go-storage/pull/846
- [x] Integration tests (we need to figure how to run integration tests on a mono repo)
  - https://github.com/beyondstorage/go-storage/pull/847
- [x] #851
- [x] Auto releases (we can build an auto release now!)
- [x] Dependence updates (https://github.com/beyondstorage/go-storage/pull/873)
- [x] Update docs and examples
  - https://github.com/beyondstorage/site/pull/255

## Progress

- We are trying to build a demo of this mono repo.
- https://go.beyondstorage.io is online, we are ready for the repo changes.
- We will migrate all code first and then update all our workflows to meet mono repo needs
- Auto release is hard for our repo, we will find a solution for it in the futher.
