### ISSUE TITLE
Service tracking issue for GSP-86: Add CreateLink Operation

### ISSUE THREAD

**Issue by Joey-1445601153** [beyondstorage/go-storage#891]
* [Rendered GSP](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/86-add-create-link-operation.md)
* [Tracking Issue](https://github.com/beyondstorage/go-storage/issues/611)
 
This is the service tracking issue that generated by go-community, please close with comments if not applicable to this project.
 
## Steps
If this service has native support for `Link` or `Symlink`:

* [ ]  Implement `CreateLink` API
* [ ]  Add support for `List`/`Stat`
* [ ]  Setup linker tests
 
If this service doesn't have native support for `Link` or `Symlink`, it's optinal to implement the `virtual_link` features:
 
* [ ]  Start a RFC to describe the way to implement the `virtual_link` feature (take this issue as the tracking issue)
* [ ]  Implement the RFC
* [ ]  Setup linker tests

**Comment by JinnyYi** [comment]
Included in https://github.com/beyondstorage/go-storage/issues/874.
