### ISSUE TITLE
services/ftp: Tracking issue for Integration Test: Implement Multi-platform Integration Test

### ISSUE THREAD

**Issue by npofsi** [beyondstorage/go-storage#898]
Track integration test implement progress.

## Steps
- [x] Basic implement: Integration test with [fclairamb/ftpserver](https://github.com/fclairamb/ftpserver) on Ubuntu
- [ ] Integration test with [Filezilla](https://filezilla-project.org/) on Windows
- [x] Integration test with [vsftpd](https://security.appspot.com/vsftpd.html) on Ubuntu
