### ISSUE TITLE
Tracking issue of GSP-837: Support Feature Flag

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#966]
- [Rendered GSP](https://github.com/beyondstorage/go-storage/pull/837)

## Steps

- [x] Add operations back to `Storager`
  - Test should not use type assertions.
- [x] Support feature flag API
  - Add `write_empty_object` in `features.toml` and add `virtual` property for virtual features.
  - Generate `ServiceFeatures` and `StorageFeatures` on go-storage side. Rename the current generated `ServiceFeatures` and `StorageFeatures` pairs and structs for services.
- [ ] Integration test supports feature flag
  - [tests: Migrate all tests to Feature and suite based](https://github.com/beyondstorage/go-storage/issues/1022)
- [x] Services migrate to go-storage
  - Update dot-import for the `types` package
